//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstatePriceForecast
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PredictionsEntities : DbContext
    {
        private static PredictionsEntities _context;

        public PredictionsEntities()
            : base("name=PredictionsEntities")
        {
        }

        public static PredictionsEntities GetContext()
        {
            if (_context == null)
                _context = new PredictionsEntities();
            return _context;
        }


        public virtual DbSet<ApartmentTypes> ApartmentTypes { get; set; }
        public virtual DbSet<MetroStations> MetroStations { get; set; }
        public virtual DbSet<PricePredictions> PricePredictions { get; set; }
        public virtual DbSet<RealEstate> RealEstate { get; set; }
        public virtual DbSet<Renovations> Renovations { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
