//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstatePriceForecast
{
    using System;
    using System.Collections.Generic;
    
    public partial class PricePredictions
    {
        public int PredictionID { get; set; }
        public int RealEstateID { get; set; }
        public decimal CurrentPrice { get; set; }
        public Nullable<decimal> PriceIn5Years { get; set; }
        public Nullable<decimal> PriceIn10Years { get; set; }
    
        public virtual RealEstate RealEstate { get; set; }
    }
}
