//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstatePriceForecast
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealEstate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RealEstate()
        {
            this.PricePredictions = new HashSet<PricePredictions>();
        }
    
        public int RealEstateID { get; set; }
        public int Rooms { get; set; }
        public decimal TotalArea { get; set; }
        public decimal LivingArea { get; set; }
        public decimal KitchenArea { get; set; }
        public int Floor { get; set; }
        public int TotalFloors { get; set; }
        public int MetroStationID { get; set; }
        public int ApartmentTypeID { get; set; }
        public int RenovationID { get; set; }
    
        public virtual ApartmentTypes ApartmentTypes { get; set; }
        public virtual MetroStations MetroStations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PricePredictions> PricePredictions { get; set; }
        public virtual Renovations Renovations { get; set; }
    }
}
